### ISSUE TITLE
Android - Unresolved reference: R

### ISSUE THREAD

**Issue by samirBloux** [zoontek/react-native-bootsplash#540] opened 2024-02-05 18:44 UTC
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Hello,
When I launch my simulator on Android, I encounter the following error: 'MainActivity.kt:26:29 Unresolved reference: R', even though I have followed the documentation correctly.

Thank you for your help :)

### Library version

5.2.2

### Environment info

```shell
System:
  OS: macOS 14.2
  CPU: (8) arm64 Apple M1
  Memory: 364.56 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 1.22.18
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 15.4
      - macOS 12.3
      - tvOS 15.4
      - watchOS 8.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 13.3.1/13E500a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/samir/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

`_android/app/src/main/res/values/styles.xml_`

```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>
    <style name="BootTheme" parent="Theme.BootSplash">
        <item name="bootSplashBackground">@color/bootsplash_background</item>
        <item name="bootSplashLogo">@drawable/bootsplash_logo</item>
        <item name="postBootSplashTheme">@style/AppTheme</item>
    </style>
</resources>
```

`_android/app/src/main/AndroidManifest.xml_`

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true"
        android:theme="@style/BootTheme">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>
</manifest>
```

### Reproducible sample code

```js
`_android/app/src/main/java/com/yourprojectname/MainActivity.kt_`


package com.koulhalalapp

import android.os.Bundle
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import com.zoontek.rnbootsplash.RNBootSplash

class MainActivity : ReactActivity() {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  override fun getMainComponentName(): String = "KoulHalalApp"

  /**
   * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
   * which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
   */
  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)

  override fun onCreate(savedInstanceState: Bundle?) {
    RNBootSplash.init(this, R.style.BootTheme) // ⬅️ initialize the splash screen
    super.onCreate(savedInstanceState) // super.onCreate(null) with react-native-screens
  }
}
```
```

**Comment by zoontek** [comment] 2024-02-05 20:42
Could you create a repository to reproduce this? Someone already reported that and I was not able to do it. Maybe spring is missing in the explanations.

**Comment by devteam-technolabs** [comment] 2024-02-07 06:16
@zoontek I too faced this issue, The issue is this import is not found

` import com.zoontek.rnbootsplash.RNBootSplash`
 
 which is causing the issue becaused RNBootSplash do not get  any references
 
![Screenshot 2024-02-07 at 11 45 57 AM](https://github.com/zoontek/react-native-bootsplash/assets/75498565/926ffa4e-0a93-4827-9026-ef42ce3f16c4)

**Comment by zoontek** [comment] 2024-02-07 10:23
@devteam-technolabs And I'm unable to reproduce it (the example app is using react native 0.73), which make me think that some users might miss something. Maybe they forget to run a Gradle sync?

**Comment by samirBloux** [comment] 2024-02-09 13:45
Hello, 
I haven't had time to publish a repository, but in my case, I encountered this error because the package name imported into the MainApplication and MainActivity files was different from what could be found in the android/app/build.gradle file.

` android/app/build.gradle`

```
    namespace "com.test2"
    defaultConfig {
        applicationId "com.test2"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 40
        versionName "1.67"
    }
```


` MainActivity`

```
package com.test // replace by com.test2

import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import android.os.Bundle
import com.zoontek.rnbootsplash.RNBootSplash
```

` MainApplication`

```
package com.test // replace by com.test2

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
```

**Comment by zoontek** [comment] 2024-02-11 10:49
Just tried to reproduce it using a fresh, new project, no issue whatsoever.

<img width="1034" src="https://github.com/zoontek/react-native-bootsplash/assets/1902323/d849665b-f1b1-4b21-b6d0-a5528fe94157">

Just in case, go to your `/android` and run a `./gradlew clean` before running `npm run android` / `yarn android` again.

**Comment by zoontek** [comment] 2024-02-22 10:51
Closing as no-one was able to provides a reproduction.

**Closed by zoontek** 2024-02-22 10:51 UTC
Labels: bug

**Comment by devteam-technolabs** [comment] 2024-02-22 13:49
@zoontek please find the reproducable code here https://we.tl/t-I8cGFKxw6Y

**Comment by devteam-technolabs** [comment] 2024-02-22 13:50
Hey @zoontek  Sorry for the delay, was bit busy.
please find the reproducable code here https://we.tl/t-I8cGFKxw6Y

**Comment by zoontek** [comment] 2024-02-22 17:40
@devteam-technolabs Are you sure you uploaded the corrected archive? This does not contains any of the CLI generated files (no `colors.xml`, no `bootsplash_logo.png`, etc) and the library is not even setted up (no `BootSplash.init` in the `MainActivity.kt`)

**Comment by devteam-technolabs** [comment] 2024-02-23 07:44
@zoontek my bad, here is the template https://we.tl/t-qgtex7k0qx

**Comment by devteam-technolabs** [comment] 2024-02-23 09:48
Thanks @zoontek for quick responses . It is fixed now, I removed everthing and then reinstalled and did gradle sync
