### ISSUE TITLE
Crash: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()'

### ISSUE THREAD

**Issue by kylecesmat** [zoontek/react-native-bootsplash#381] opened 2022-08-12 16:08 UTC
### Bug summary

This crash occurs when a Pixel user backgrounds the application before the splashscreen finishes & the `hide` method can be invoked.

Initially I filed a crash report w/ Google but their response suggests this can be avoided on v12 by perhaps trying to unregister `setOnExitAnimationListener`, as well as stop any other Splash screen animation/logic - possibly when the activity `onPause` is invoked?

Crash report: https://issuetracker.google.com/issues/242118185?pli=1

This is likely occurring near this line https://github.com/zoontek/react-native-bootsplash/blob/master/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java#L124

### Library version

4.3.1

### Environment info

```shell
SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
```

### Steps to reproduce

1. Open an app with react-native-bootscreen
2. Before the bootscreen completes, background the app
3. Open the app back up and notice a crash

### Reproducible sample code

```js
Should be reproducible in sample app on a Google Pixel device.
```

**Comment by tr3v3r** [comment] 2022-10-06 08:35
Hi. The same here.
https://issuetracker.google.com/issues/242118185

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/23724142/194263545-4d5c55b1-b149-443c-950a-42382989c966.png">

**Comment by wakie92** [comment] 2023-02-07 01:18
I've experienced same issue. Is there any update the issue?

**Comment by claudiozam** [comment] 2023-04-10 12:30
Same issue. Android 12 on Samsung SM-X800 device.

**Comment by saadi-ninjasCode** [comment] 2023-04-28 07:42
Android 13   users facing this issue. 

![Screenshot 2023-04-28 at 12 42 02 PM](https://user-images.githubusercontent.com/57723965/235085908-62138c84-6e9c-44b9-8d02-d13900d159a1.png)

**Comment by iferden** [comment] 2023-05-03 13:22
We're facing the same issue on Android 13. 

<img src='https://user-images.githubusercontent.com/76057122/235928219-55e2b348-016d-4d7f-9b6c-4d2de2869930.png' width='400' />

**Comment by techgerm** [comment] 2023-06-01 20:41
We started seeing this crash as well after migrating from `react-native-splash-screen` to `react-native-bootsplash`:

![Screenshot 2023-06-01 at 1 40 29 PM](https://github.com/zoontek/react-native-bootsplash/assets/38846104/613ff64d-980c-4f41-bc0d-be9624c79a1a)

**Comment by roneyyb** [comment] 2023-06-02 05:45
We are also seeing this crash. What is the fix for this?

**Comment by devoren** [comment] 2023-06-04 12:01
+1, same issue

**Comment by KolissnikBogdan** [comment] 2023-06-15 13:02
same +1

**Comment by Roamer77** [comment] 2023-07-11 08:08
same +1

**Comment by Soap-141** [comment] 2023-07-27 17:47
Same

**Comment by a-petrenko-muse** [comment] 2023-07-28 07:27
Same

**Comment by zoontek** [comment] 2023-07-28 07:58
Could you please just upvote with emojis on the initial message instead of spamming?

No need to trigger notifications for everyone watching this thread just to say "Same".

This is indeed an Android SplashScreen API issue, we cannot do much here.

**Comment by zoontek** [comment] 2023-07-28 21:43
I investigated a bit, and can reproduce it.

The issue is kinda hard to solve since even if I implement a `LifecycleEventListener`, call `activity.getSplashScreen().clearOnExitAnimationListener()` on activity pause, it's already too late:

https://github.com/zoontek/react-native-bootsplash/assets/1902323/ec827aa6-84de-4541-8251-d091bb5ed202

The effect is what appears to be a restart of the UI, but it has no impact on the app itself.

**Comment by LonelyCpp** [comment] 2023-08-08 09:43
@zoontek since a complete fix might take you or the community longer to implement, can you recommend a workaround? 

would you recommend [this](https://github.com/zoontek/react-native-bootsplash/issues/381#issuecomment-1280676140) comment? even if it means that some feature will stop working, it might be better than an outright crash.

thanks!

**Comment by zoontek** [comment] 2023-08-08 13:57
@LonelyCpp I would not recommend it, for a pretty good reason. And it's that the fix might probably already be there: https://github.com/zoontek/react-native-bootsplash/pull/475

Bye AndroidX 👋

https://github.com/zoontek/react-native-bootsplash/assets/1902323/83db745e-8e47-4295-822e-933f99a4855e

**Comment by zoontek** [comment] 2023-08-21 22:08
Version 5.0.0 is available: https://github.com/zoontek/react-native-bootsplash/releases/tag/5.0.0

**Closed by zoontek** 2023-08-21 22:08 UTC
Labels: bug

**Comment by Abhishek25031991** [comment] 2024-01-02 07:06
Facing the same issue in the 5.0 version also

**Comment by tdinckaya** [comment] 2025-02-06 21:07
In version 6.3.2 I have the same problem. :(
