### ISSUE TITLE
iOS 15  throws "react-native-bootsplash has not been initialized"

### ISSUE THREAD

**Issue by helenaford** [zoontek/react-native-bootsplash#264] opened 2021-08-18 12:01 UTC
### Bug summary

Having reports from sentry of errors in production for iOS 15 when calling `RNBootSplash.hide({ fade: false })` that:
`react-native-bootsplash has not been initialized
`
Any help with this would be appreciated - it's affecting a lot of our users.

### Library version

3.2.4

### Environment info

```shell
info Fetching system and libraries information...
(node:36763) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.46 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 19, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 24.0.1, 24.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Open the app

### Reproducible sample code

```js
RNBootSplash.hide({ fade: false })
```

**Comment by zoontek** [comment] 2021-08-19 09:56
Unfortunately I didn't update to the iOS beta yet, as it seems pretty unstable for now. I will keep you in touch when it's done.

**Comment by helenaford** [comment] 2021-08-30 22:11
@zoontek thanks for the response. 

After some more digging, it seems to be when the app is woken up by an incoming push notification, and I'm guessing it'll happen for any background task that wakes up the app.

The `didFinishLaunchingWithOptions` method in `AppDelegate.m` is called, but `rootView` is null, so when bootsplash is initialised, `[RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];` it fails. And then when the app is opened before the background task has finished, it's not initialized, and there's a black screen for a few seconds on launch.

This shows up in the native logs `react-native-bootsplash has been initialized too early: rootViewController must be set`

```
UIViewController *rootVC = RCTPresentedViewController();

  if (!rootVC) {
    RCTLogError(@"react-native-bootsplash has been initialized too early: rootViewController must be set");
    return;
  }
```

Looks like a new thing for iOS 15. Appreciate any thoughts on how this can be solved.

Also, wanted to say a thank you for creating and maintaining an awesome library. I use it in many of my apps.

**Comment by zoontek** [comment] 2021-09-05 09:13
@helenaford Could you post your `AppDelegate.m` file?

**Comment by zoontek** [comment] 2021-09-05 09:45
I couldn't reproduce the issue, do you have a reproduction case?

https://user-images.githubusercontent.com/1902323/132122450-30c07cf2-51f3-4bda-b976-f4d0f7981710.mp4

**Comment by helenaford** [comment] 2021-09-05 10:10
What does you push payload look like? It could potential be to do with the 'content-available' flag be set to true which wakes up the app

**Comment by zoontek** [comment] 2021-09-05 10:13
@helenaford It's an iOS 15 push notification (public beta 8).

**Comment by zoontek** [comment] 2021-09-05 10:14
@helenaford Could you publish your `AppDelegate.m`? I just wanna check something really quickly 🙂

**Comment by helenaford** [comment] 2021-09-05 11:46
@zoontek i won't be able to check with beta 8 until later today, the iOS 15 push should still have the flag 'content-available' but you need to also enable background modes with remote notifications and fetch

**Comment by pnthach95** [comment] 2021-09-09 14:41
This bug is weird. I tried running 3 projects with the same version of bootsplash (3.2.5) on iOS 14.5 Simulator. Only 1 project has bug.
Somehow, bootsplash was hidden before `RNBootSplash.hide()`, phone screen is black while bundling.

![image](https://user-images.githubusercontent.com/31266357/132704388-02b4d8d4-2826-471d-b41c-f7baf9bc4f5c.png)

Some bugged project's information:

AppDelegate.m

```objective-c
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import "RNBootSplash.h"
#import <GoogleMaps/GoogleMaps.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [GMSServices provideAPIKey:@"your key"];
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"project name"
                                            initialProperties:nil];

  if (@available(iOS 13.0, *)) {
      rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
      rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];

  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```
package.json
```json
"dependencies": {
    "@codler/react-native-keyboard-aware-scroll-view": "^2.0.0",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/netinfo": "^6.0.2",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-native-picker/picker": "^1.16.5",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/devtools": "^6.0.1",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^6.0.7",
    "@reduxjs/toolkit": "^1.6.1",
    "axios": "^0.21.4",
    "dayjs": "^1.10.6",
    "formik": "^2.2.9",
    "numbro": "^2.3.5",
    "react": "17.0.2",
    "react-native": "0.64.2",
    "react-native-bootsplash": "^3.2.5",
    "react-native-camera": "^4.1.1",
    "react-native-device-info": "^8.3.1",
    "react-native-fast-image": "^8.3.7",
    "react-native-geolocation-service": "^5.3.0-beta.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localization": "^2.1.7",
    "react-native-localize": "^2.1.4",
    "react-native-maps": "0.29.3",
    "react-native-mmkv-storage": "^0.6.0",
    "react-native-paper": "^4.9.2",
    "react-native-permissions": "^3.0.5",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "^2.2.0",
    "react-native-render-html": "^6.1.0",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.6.0",
    "react-native-skeleton-placeholder": "^5.0.0",
    "react-native-table-component": "^1.2.1",
    "react-native-vector-icons": "^8.1.0",
    "react-redux": "^7.2.5",
    "redux": "^4.1.1",
    "redux-thunk": "^2.3.0",
    "yup": "^0.32.9"
  }
```

**Comment by pnthach95** [comment] 2021-09-09 19:17
So I just found out that enabling Supporting Multiple Windows causes bug. When app is opened, screen turns black, `getVisibilityStatus` return `hidden`.

![image](https://user-images.githubusercontent.com/31266357/132748552-ad1abe8f-51c1-4e42-92f6-881045b82440.png)

**Comment by efstathiosntonas** [comment] 2021-09-16 12:47
@zoontek any updates? iOS 15 release date is set to 20th  September. Thanks

**Comment by zoontek** [comment] 2021-09-16 13:09
@efstathiosntonas Nobody submitted a fix for the moment.

**Comment by oberruti** [comment] 2021-09-20 15:23
Same problem here but without iOS 15. Just using the `.hide()` and it's showing the same error:
`[Error: react-native-bootsplash has not been initialized, or has been too early]`

**Comment by sezginriggs** [comment] 2021-09-22 08:25
same problem here and Apple AppStore rejects new releases because of that problem.

**Comment by zoontek** [comment] 2021-09-22 08:26
@oberruti @sezginriggs Are you sur it's called at the right time? https://github.com/zoontek/react-native-bootsplash#ios-1

**Comment by sezginriggs** [comment] 2021-09-22 08:30
@zoontek yes, as instructed on documents.

**Comment by zoontek** [comment] 2021-09-22 08:54
I rolled back 3.2.4 changes: https://github.com/zoontek/react-native-bootsplash/releases/tag/3.2.6 as a temporary solution.

**Comment by oberruti** [comment] 2021-09-22 13:18
@zoontek I didn't add anything to the `AppDelegate.m` because I created the Splash Screen with the suggested command and it looks okay in the simulator. But I'm pretty sure I'm calling `.hide()` at the right moment.

**Comment by zoontek** [comment] 2021-09-22 13:40
@oberruti Ok, you have to do it.

**Comment by oberruti** [comment] 2021-09-22 14:03
> @oberruti Ok, you have to do it.

@zoontek Okay, this step too: `Set the BootSplash.storyboard as launch screen file:` ?

**Comment by zoontek** [comment] 2021-09-22 14:05
@oberruti Just follow the README, everything is in it.

**Comment by helenaford** [comment] 2021-10-30 12:45
@zienna nope. it's still happening 😢 it's our top 3rd bug in production. Luckily the user doesn't really notice too much as the app still opens up.

Do you experience this bug too with push notifications?

**Comment by zoontek** [comment] 2021-10-30 19:39
@helenaford Do you catch an eventual promise rejection, like in the example app? https://github.com/zoontek/react-native-bootsplash/blob/6fa19df01ffef6af45166b4a71f78b13d4f2c7bd/example/App.js#L20

It's not perfect, but it will not appear in your Sentry backlog

**Comment by zoontek** [comment] 2021-11-15 11:01
The new version does not reject promises anymore, try it out.

**Comment by zoontek** [comment] 2022-01-22 16:50
I'm closing this since no-one seems to experience the issue anymore

**Closed by zoontek** 2022-01-22 16:50 UTC
Labels: bug

**Comment by juanjlunar** [comment] 2022-02-04 23:57
`
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import "RNBootSplash.h" // <- add the header import

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // …
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name

  return YES;
}
`
This is coming from the documentation.

Where does rootView is coming from ? my project doesn't hace that variable there.

**Comment by pnthach95** [comment] 2022-02-05 00:43
> ` #import "AppDelegate.h"
> 
> #import <React/RCTBridge.h>
> #import <React/RCTBundleURLProvider.h>
> #import <React/RCTRootView.h>
> 
> #import "RNBootSplash.h" // <- add the header import
> 
> @implementation AppDelegate
> 
>     * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
>       {
>       // …
>       rootViewController.view = rootView;
>       self.window.rootViewController = rootViewController;
>       [self.window makeKeyAndVisible];
>       [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name
>       return YES;
>       }
>       `
>       This is coming from the documentation.
> 
> 
> Where the rootView is coming from ? my project doesn't hace that variable there.

It's always have when you create project

`RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge`

**Comment by juanjlunar** [comment] 2022-02-05 00:44
> > ` #import "AppDelegate.h"
> > #import <React/RCTBridge.h>
> > #import <React/RCTBundleURLProvider.h>
> > #import <React/RCTRootView.h>
> > #import "RNBootSplash.h" // <- add the header import
> > @implementation AppDelegate
> > ```
> > * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> >   {
> >   // …
> >   rootViewController.view = rootView;
> >   self.window.rootViewController = rootViewController;
> >   [self.window makeKeyAndVisible];
> >   [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name
> >   return YES;
> >   }
> >   `
> >   This is coming from the documentation.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Where the rootView is coming from ? my project doesn't hace that variable there.
> 
> It's always have when you create project
> 
> `RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge`

No mine doesn't, its a RN 0.66 version project.

**Comment by pnthach95** [comment] 2022-02-05 01:32
> > > ` #import "AppDelegate.h"
> > > #import <React/RCTBridge.h>
> > > #import <React/RCTBundleURLProvider.h>
> > > #import <React/RCTRootView.h>
> > > #import "RNBootSplash.h" // <- add the header import
> > > @implementation AppDelegate
> > > ```
> > > * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> > >   {
> > >   // …
> > >   rootViewController.view = rootView;
> > >   self.window.rootViewController = rootViewController;
> > >   [self.window makeKeyAndVisible];
> > >   [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name
> > >   return YES;
> > >   }
> > >   `
> > >   This is coming from the documentation.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Where the rootView is coming from ? my project doesn't hace that variable there.
> > 
> > 
> > It's always have when you create project
> > `RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge`
> 
> No mine doesn't, its a RN 0.66 version project.

If you find `RCTRootView *rootView` in `ios` folder and get 0 results, then you should create new project and use it

**Comment by juanjlunar** [comment] 2022-02-05 01:40
> > > > ` #import "AppDelegate.h"
> > > > #import <React/RCTBridge.h>
> > > > #import <React/RCTBundleURLProvider.h>
> > > > #import <React/RCTRootView.h>
> > > > #import "RNBootSplash.h" // <- add the header import
> > > > @implementation AppDelegate
> > > > ```
> > > > * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> > > >   {
> > > >   // …
> > > >   rootViewController.view = rootView;
> > > >   self.window.rootViewController = rootViewController;
> > > >   [self.window makeKeyAndVisible];
> > > >   [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name
> > > >   return YES;
> > > >   }
> > > >   `
> > > >   This is coming from the documentation.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Where the rootView is coming from ? my project doesn't hace that variable there.
> > > 
> > > 
> > > It's always have when you create project
> > > `RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge`
> > 
> > 
> > No mine doesn't, its a RN 0.66 version project.
> 
> If you find `RCTRootView *rootView` in `ios` folder and get 0 results, then you should create new project and use it

I managed to make the splash screen appear but it dismiss before the bridge loads.
This is my AppDelegate.m

`
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = application.inputViewController;
  rootViewController.view = application.inputView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  
  [FIRApp configure]; // Firebase SDK
  [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions]; // RNNavigation

//  Facebook init sdk
  [[FBSDKApplicationDelegate sharedInstance] application:application
                          didFinishLaunchingWithOptions:launchOptions];
  
  [RNBootSplash initWithStoryboard:@"LaunchScreen" rootView:application.inputView]; // <- initialization using the storyboard file name
  
  return YES;
}
`

**Comment by pnthach95** [comment] 2022-02-05 03:48
> > > > > ` #import "AppDelegate.h"
> > > > > #import <React/RCTBridge.h>
> > > > > #import <React/RCTBundleURLProvider.h>
> > > > > #import <React/RCTRootView.h>
> > > > > #import "RNBootSplash.h" // <- add the header import
> > > > > @implementation AppDelegate
> > > > > ```
> > > > > * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> > > > >   {
> > > > >   // …
> > > > >   rootViewController.view = rootView;
> > > > >   self.window.rootViewController = rootViewController;
> > > > >   [self.window makeKeyAndVisible];
> > > > >   [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name
> > > > >   return YES;
> > > > >   }
> > > > >   `
> > > > >   This is coming from the documentation.
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Where the rootView is coming from ? my project doesn't hace that variable there.
> > > > 
> > > > 
> > > > It's always have when you create project
> > > > `RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge`
> > > 
> > > 
> > > No mine doesn't, its a RN 0.66 version project.
> > 
> > 
> > If you find `RCTRootView *rootView` in `ios` folder and get 0 results, then you should create new project and use it
> 
> I managed to make the splash screen appear but it dismisses before the bridge loads. This is my AppDelegate.m
> 
> ` @implementation AppDelegate
> 
>     * (BOOL)application:(UIApplication *)application
>       didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
>       {
>       #ifdef FB_SONARKIT_ENABLED
>       InitializeFlipper(application);
>       #endif
>       self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
>       UIViewController *rootViewController = application.inputViewController;
>       rootViewController.view = application.inputView;
>       self.window.rootViewController = rootViewController;
>       [self.window makeKeyAndVisible];
>       [FIRApp configure]; // Firebase SDK
>       [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions]; // RNNavigation
> 
> 
> // Facebook init sdk [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
> 
> [RNBootSplash initWithStoryboard:@"LaunchScreen" rootView:application.inputView]; // <- initialization using the storyboard file name
> 
> return YES; } `

I see you're using React Native Navigation. [Old README](https://github.com/zoontek/react-native-bootsplash/commit/35cdf62cf2c4cf9cee73d1a8cad457fbf8d31c68) said that `This library does not support react-native-navigation`. I don't know if current version supports RNN now so they remove that warning line. You should create new issue.

**Comment by juanjlunar** [comment] 2022-02-05 18:54
> > > > > > ` #import "AppDelegate.h"
> > > > > > #import <React/RCTBridge.h>
> > > > > > #import <React/RCTBundleURLProvider.h>
> > > > > > #import <React/RCTRootView.h>
> > > > > > #import "RNBootSplash.h" // <- add the header import
> > > > > > @implementation AppDelegate
> > > > > > ```
> > > > > > * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> > > > > >   {
> > > > > >   // …
> > > > > >   rootViewController.view = rootView;
> > > > > >   self.window.rootViewController = rootViewController;
> > > > > >   [self.window makeKeyAndVisible];
> > > > > >   [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name
> > > > > >   return YES;
> > > > > >   }
> > > > > >   `
> > > > > >   This is coming from the documentation.
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Where the rootView is coming from ? my project doesn't hace that variable there.
> > > > > 
> > > > > 
> > > > > It's always have when you create project
> > > > > `RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge`
> > > > 
> > > > 
> > > > No mine doesn't, its a RN 0.66 version project.
> > > 
> > > 
> > > If you find `RCTRootView *rootView` in `ios` folder and get 0 results, then you should create new project and use it
> > 
> > 
> > I managed to make the splash screen appear but it dismisses before the bridge loads. This is my AppDelegate.m
> > ` @implementation AppDelegate
> > ```
> > * (BOOL)application:(UIApplication *)application
> >   didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> >   {
> >   #ifdef FB_SONARKIT_ENABLED
> >   InitializeFlipper(application);
> >   #endif
> >   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
> >   UIViewController *rootViewController = application.inputViewController;
> >   rootViewController.view = application.inputView;
> >   self.window.rootViewController = rootViewController;
> >   [self.window makeKeyAndVisible];
> >   [FIRApp configure]; // Firebase SDK
> >   [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions]; // RNNavigation
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > // Facebook init sdk [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
> > [RNBootSplash initWithStoryboard:@"LaunchScreen" rootView:application.inputView]; // <- initialization using the storyboard file name
> > return YES; } `
> 
> I see you're using React Native Navigation. [Old README](https://github.com/zoontek/react-native-bootsplash/commit/35cdf62cf2c4cf9cee73d1a8cad457fbf8d31c68) said that `This library does not support react-native-navigation`. I don't know if current version supports RNN now so they remove that warning line. You should create new issue.

Thanks im going back to react-native-splash-screen, I fixed an issue with firebase.
