### ISSUE TITLE
Dependencies upgrade

### ISSUE THREAD

**Issue by mydesweb** [zoontek/react-native-bootsplash#353] opened 2022-05-05 11:20 UTC
### Why it is needed?

I noticed that there are new versions for some android/app/build.gradle dependencies
```
implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0" // new version is 1.1.0
implementation "androidx.core:core-splashscreen:1.0.0-beta01" // new version beta02
```
I already did the update and everything is working, what do you think? It is safe to update them?

### Possible implementation

```
implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
implementation "androidx.core:core-splashscreen:1.0.0-beta02"
```

**Comment by zoontek** [comment] 2022-05-05 11:22
Duplicate of https://github.com/zoontek/react-native-bootsplash/pull/345

`androidx.swiperefreshlayout:swiperefreshlayout` is not related to react-native-bootsplash, you can update it

**Closed by zoontek** 2022-05-05 11:22 UTC
Labels: feature request
