### ISSUE TITLE
[ANDROID] Icon is not displayed at first launch

### ISSUE THREAD

**Issue by Aurelienlajoinie** [zoontek/react-native-bootsplash#357] opened 2022-06-13 14:01 UTC
### Bug summary

Hello,

First thank you for the work on this library which greatly facilitates the integration of splashcreen on a react-native application :) 

The issue i experiment is the following: the splashscreen launches correctly, however, on the very first launch, the icon is not displayed, only the background is visible. 
Then all the other openings of the application work as expected and shows the background and the icon.

### Library version

4.1.5

### Environment info

```shell
react-native-bootsplash: 4.1.5
react-native: 0.66.4
Android target API: 31

react-native info output:

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 37.14 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.05.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
```
```


### Steps to reproduce

1. Build android application
2. Install APK on an android 12 device
3. Launch the application => Icon is not visible
4.  Kill the app and launch it again => all works fine


### Reproducible sample code

```js
MainActivity.java

 @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected void loadApp(String appKey) {
        RNBootSplash.init(getPlainActivity()); // <- initialize the splash screen
        super.loadApp(appKey);
      }
    };
  }
```
style.xml:
```
  <!-- BootTheme should inherit from Theme.SplashScreen -->
  <style name="BootTheme" parent="Theme.SplashScreen">
    <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
    <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
    <item name="postSplashScreenTheme">@style/AppTheme</item>
  </style>

```
```

**Comment by zoontek** [comment] 2022-06-13 14:03
Duplicate of https://github.com/zoontek/react-native-bootsplash/issues/319#issuecomment-1107455209

**Closed by zoontek** 2022-06-13 14:03 UTC
Labels: duplicate
