### ISSUE TITLE
[Android] Splash screen image is scaled

### ISSUE THREAD

**Issue by vlkpa** [zoontek/react-native-bootsplash#306] opened 2022-01-24 16:24 UTC
### Bug summary

Splash screen image is scaled.
![271837581_653397636079880_4870433056114577204_n](https://user-images.githubusercontent.com/78504015/150821237-5e2c7b5c-412f-4451-996f-4a35c3df8173.jpg)

### Library version

4.1.0

### Environment info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 10.97 GB / 31.40 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.17.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: Not Found
  Languages:
    Java: 15.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Integrate this library into project following Readme (migrate from react-native-splash-screen)
2. Generate bootsplash using React logo from example project `yarn react-native generate-bootsplash src/assets/logo/bootsplash_logo_original.png --background-color=73be46`
3. Open app
**styles.xml**
`
<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:textColor">#000000</item>
        <item name="android:statusBarColor">@color/CZUgrey</item>
    </style>

    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>
</resources>
`

**AndroidManifest.xml**
`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="com.ttt.mobile.android">

  

  <application
    android:name=".MainApplication"
    android:label="@string/app_name"
    android:icon="@mipmap/ic_launcher"
    android:roundIcon="@mipmap/ic_launcher"
    android:allowBackup="false"
    tools:replace="android:allowBackup"
    android:usesCleartextTraffic="true"
    android:networkSecurityConfig="@xml/network_security_config"
    android:theme="@style/BootTheme">
    <meta-data
      android:name="com.google.ar.core"
      android:value="optional"/>

    <activity
      android:name=".MainActivity"
      android:label="@string/app_name"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
      android:launchMode="singleTask"
      android:usesCleartextTraffic="true"
      android:windowSoftInputMode="adjustResize"
      android:screenOrientation="portrait"
      android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>

        <data android:scheme="tttmobile"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>

    <activity
      android:name="com.facebook.react.devsupport.DevSettingsActivity"
      android:exported="false"/>

    
  </application>

</manifest>
`
**android/build.gradle** -same as Readme

**android/app/build.gradle** -same as Readme

**MainActivity.java** -same as Readme

### Reproducible sample code

```js
import * as BootSplash from 'react-native-bootsplash';

export const App = () => {
  useEffect(() => {
    setTimeout(() => BootSplash.hide(), 4000);
  }, []);

  return (
    <>
      <AppMenu />
    </>
  );
};

export default App;
```

**Comment by zoontek** [comment] 2022-01-24 16:30
Use the CLI assets generator.

**Comment by vlkpa** [comment] 2022-01-25 05:33
Yes, I am using CLI assets generator with logo from [example ](https://github.com/zoontek/react-native-bootsplash/tree/master/example/assets)project.
`yarn react-native generate-bootsplash src/assets/logo/bootsplash_logo_original.png --background-color=73be46`
![image](https://user-images.githubusercontent.com/78504015/150916639-5a620049-ea23-49ab-aa14-7d024e9de5d7.png)

I want to migrate from react-native-splash-screen. Also removed `mimap-anydpi-v26` folder as 
[here](https://github.com/zoontek/react-native-bootsplash/issues/304#issuecomment-1013744838)

**Comment by AmirDiafi** [comment] 2022-01-25 10:46
+1

**Comment by zoontek** [comment] 2022-01-25 17:19
Can you publish a repository to reproduce the issue?

**Comment by AmirDiafi** [comment] 2022-01-25 23:16
I fixed it by removing the width from the logo generator command:

```
yarn react-native generate-bootsplash assets/bootsplash_logo_original.png \ 
  --background-color=8EF9C3 \
  --assets-path=assets \
  --flavor=main
  ```

**Comment by zoontek** [comment] 2022-01-31 10:48
@vlkpa Please publish a repository so I can help or I will close this issue, thanks.

**Comment by anija** [comment] 2022-02-01 15:10
I had the same problem, this is my workaround:
* yarn react-native generate-bootsplash <PATH>
* copy the generated bootsplash_logo.png inside mipmap-xxhdpi
* paste it to drawable-xhdpi
* use the drawable in styles: <item name="windowSplashScreenAnimatedIcon">@drawable/bootsplash_logo</item>

**Closed** 2022-02-04 17:18 UTC
Labels: bug

**Comment by anija** [comment] 2022-02-04 18:10
Closed? It's a bug a lot of us are experiencing.

**Comment by zoontek** [comment] 2022-02-04 18:12
@anija Yes, I couldn't reproduce it and didn't have a reproduction repository.

**Comment by Thanaen** [comment] 2022-03-17 09:09
Hi @zoontek 
What does it mean to "regenerate assets"?

**Comment by zoontek** [comment] 2022-03-17 09:14
@Thanaen Re-run the CLI `react-native generate-bootsplash` command

**Comment by maxperry** [comment] 2022-03-21 13:41
I was having the same issue. Moving all the generated files from `mimap-*` to the respective `drawable-*` folders as suggested by @anija fixed it for me.
