### ISSUE TITLE
Android Import not working in MainActivity.java

### ISSUE THREAD

**Issue by kobagapu** [zoontek/react-native-bootsplash#204] opened 2021-02-08 09:46 UTC
import com.zoontek.rnbootsplash.RNBootSplash;
 IOS Working fine
![Screenshot 2021-02-08 at 3 17 04 PM](https://user-images.githubusercontent.com/61305724/107202863-b4380500-6a20-11eb-9aac-aa2814774a0e.png)

**Comment by tomLadder** [comment] 2021-02-08 12:22
I have the same issue.

**Comment by zoontek** [comment] 2021-02-08 14:30
@kobagapu @tomLadder @MaxHaider Details please? Which version?

**Comment by MaxHaider** [comment] 2021-02-09 08:09
@zoontek 
After installed the latest version (3.1.3) the import in MainActivity.java stopped working.
![image](https://user-images.githubusercontent.com/22192150/107333579-f8291980-6ab5-11eb-9a69-d09f8d81cac5.png)
Downgrading the Version to 3.1.0 also didn't help.

Versions:
node: v12.14.1
react-native-bootsplash: v3.1.3 / 3.1.2 / 3.1.0

**Comment by zoontek** [comment] 2021-02-09 08:10
@MaxHaider Did you do a Gradle sync / a cache clean?

**Comment by MaxHaider** [comment] 2021-02-09 08:10
yes

**Comment by zoontek** [comment] 2021-02-09 08:11
@MaxHaider Are you opening Android studio on the /android directory (not the root one!)

**Comment by MaxHaider** [comment] 2021-02-09 08:12
yes of course x)

**Comment by zoontek** [comment] 2021-02-09 08:16
@MaxHaider I said that because I just tried it with a fresh project (RN 0.63.4, RN-bootsplash 3.1.3) and everything went fine.

<img width="754" alt="Screenshot 2021-02-09 at 09 15 53" src="https://user-images.githubusercontent.com/1902323/107334787-73d79600-6ab7-11eb-8ee8-65f79de3f861.png">

<img width="1193" alt="Screenshot 2021-02-09 at 09 15 30" src="https://user-images.githubusercontent.com/1902323/107334816-7df99480-6ab7-11eb-98f3-fb068509988b.png">

**Comment by zoontek** [comment] 2021-02-09 08:20
> After installed the latest version (3.1.3) the import in MainActivity.java stopped working.
> Downgrading the Version to 3.1.0 also didn't help.

If it worked before the rollback and as the dependencies from npm doesn't change, this cannot be related to the lib.
Try using https://github.com/pmadruga/react-native-clean-project

**Comment by MaxHaider** [comment] 2021-02-09 09:09
🤔 
I cloned an existing one and installed the node modules there.

Just ran react-native-clean-project, it sadly didn't solve the problem.

**Comment by zoontek** [comment] 2021-02-09 09:10
@MaxHaider The issue is probably with the cloned project then. Which RN does it use?

**Comment by MaxHaider** [comment] 2021-02-09 09:11
v0.63.4

**Comment by zoontek** [comment] 2021-02-09 17:14
Try with a fresh project and compare it to this existing project then.

**Comment by MaxHaider** [comment] 2021-02-10 09:06
Update:
After manually linking the lib I could finally build the project.

The problem is, the splashscreen doesn't disappear now.
If i don't call RNBootSplash.init, it works just fine (but without the splashscreen of course)

**Comment by zoontek** [comment] 2021-02-10 09:21
> Update:
> After manually linking the lib I could finally build the project.
> 
> The problem is, the splashscreen doesn't disappear now.
> If i don't call RNBootSplash.init, it works just fine (but without the splashscreen of course)
> 
> edit:
> When trying to call RNBootSplash.hide the following error occurs:
> `[TypeError: null is not an object (evaluating 'NativeModule.hide')]`

The module seems not being linked. Something is wrong in your (auto)linking config

**Comment by adapptor-kurt** [comment] 2021-02-16 01:58
I'm having the same problem in 3.1.4, and could fix it by adding the manual linking config to settings.gradle:
```
include ':react-native-bootsplash'
project(':react-native-bootsplash').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-bootsplash/android')
```

This project has yarn workspaces, and some extra resolver config in metro.config.js to find dependencies in other places, but I'd be surprised if that's the cause.  We have many other RN packages and this is the only one which doesn't autolink correctly on Android.  RN does add `new RNBootSplashPackage()` to PackageList, but just not the settings.gradle config.  Autolinking works fine for iOS.

**Comment by zoontek** [comment] 2021-02-16 07:22
@adapptor-kurt Did it worked on previous versions? And did it continue to happen when your rollback?

**Comment by adapptor-kurt** [comment] 2021-02-17 05:53
@zoontek it seems to have resolved itself now.  I have been switching branches so it's difficult to know what fixed it, but I would recommend anyone having this problem try an Invalidate Caches/Restart in Android Studio and/or a git clean.

**Comment by zoontek** [comment] 2021-02-23 09:55
I'm closing this since it seems impossible to reproduce.

**Closed by zoontek** 2021-02-23 09:55 UTC
Labels: no issue template

**Comment by AlixH** [comment] 2022-09-27 13:41
> I'm having the same problem in 3.1.4, and could fix it by adding the manual linking config to settings.gradle:
> 
> ```
> include ':react-native-bootsplash'
> project(':react-native-bootsplash').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-bootsplash/android')
> ```
> 
> This project has yarn workspaces, and some extra resolver config in metro.config.js to find dependencies in other places, but I'd be surprised if that's the cause. We have many other RN packages and this is the only one which doesn't autolink correctly on Android. RN does add `new RNBootSplashPackage()` to PackageList, but just not the settings.gradle config. Autolinking works fine for iOS.

With version 4.3.2, I encounter the same issue. Indeed, just adding the config in settings.gradle solved the problem. Doing the whole manual linking process causes a package declaration duplication error
