### ISSUE TITLE
[Android 14] [Samsung S22+] App icon appearing on launch screen before launch screen icon

### ISSUE THREAD

**Issue by AlixH** [zoontek/react-native-bootsplash#536] opened 2024-01-31 10:13 UTC
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

When launching the app from quit state, we see the app icon appearing for few seconds/less than a second and then the launch screen icon shows as expected. When the app icon is shown, the background color also seem to be 'random' or maybe picked from the logo itself from the OS

I am not able to reproduce the issue on Android 13

Here is a clip of the issue on Android 14 showing the bug

https://github.com/zoontek/react-native-bootsplash/assets/32574035/a4130093-31f4-42fb-9596-1ec0764de760

Here are two screenshots from the clip to capture the issue

1) At opening we can see while the app does not fill the screen yet the app icon is shown

<img src="https://github.com/zoontek/react-native-bootsplash/assets/32574035/88787318-d12e-4ae9-b5ae-de55b6837aa8" width="300">

2) Just after the expected behavior is resumed with the good background color and icon

<img src="https://github.com/zoontek/react-native-bootsplash/assets/32574035/47622d15-0c0b-4ddf-8279-68ec0f49c645" width="300">

### Library version

5.3.0

### Environment info

```shell
System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 118.09 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /Users/alixhumbert/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.1.0 
    react-native: 0.70.14 => 0.70.14 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Close the app
2. Open the app from qui state on Android 14 device
3. Notice the app icon shows for few secs before launch screen

### Reproducible sample code

```js
TBD
```

**Comment by zoontek** [comment] 2024-01-31 10:26
Impossible to reproduce on Android 14:

**Comment by zoontek** [comment] 2024-01-31 10:28
I see that your icon is distorted, that's probably what you are seeing here:

<img width="205" alt="Screenshot 2024-01-31 at 11 27 47" src="https://github.com/zoontek/react-native-bootsplash/assets/1902323/ec9a83d8-c28c-465a-a862-412b1cb1a4fa">

**Comment by AlixH** [comment] 2024-01-31 10:29
It's only from time to time, not every time I launch the app. Can it be a Samsung thing ? 
I posted this 'testapp' to not show the actual app I am working on but our logo is not distorted

**Comment by zoontek** [comment] 2024-01-31 10:34
Yeah, Samsung is terrible at respecting the SplashScreen API. A lot of issues are coming from them.

If you are not able to reproduce it on Pixels, I recommend you to publish the issue to https://issuetracker.google.com/issues, as we will not be able to perform magic here (the first frames are handled by the system, not your app / this library)

**Comment by AlixH** [comment] 2024-01-31 11:04
Ok thank you :) 
To be noted that I cannot repoduce it on Android 13 even on a Samsung 
So it's probably the new version of UI 6.0

**Comment by zoontek** [comment] 2024-01-31 11:09
Unfortunately Samsung fork a lot of Android things in OneUI, but don't provide a simulator for developers to test. I wish those phones could disappear 😅

**Comment by AlixH** [comment] 2024-01-31 11:23
What I find surprising is that the transition is like bad -> good (right icon and background color) -> bad and then good 
See:

<img width="291" alt="Screenshot 2024-01-31 at 12 20 17" src="https://github.com/zoontek/react-native-bootsplash/assets/32574035/ec1bbaff-5249-47a8-b0cc-397fa6c6a51f">


<img width="288" alt="Screenshot 2024-01-31 at 12 20 01" src="https://github.com/zoontek/react-native-bootsplash/assets/32574035/33eacb7f-7836-401f-bd94-a5f769ff462c">

<img width="304" alt="Screenshot 2024-01-31 at 12 20 31" src="https://github.com/zoontek/react-native-bootsplash/assets/32574035/3667937f-c91d-4048-9e2d-a026eaedbb56">

<img width="303" alt="Screenshot 2024-01-31 at 12 22 13" src="https://github.com/zoontek/react-native-bootsplash/assets/32574035/47ddd6bd-e9be-4b61-8cac-a12a94059149">

**Comment by zoontek** [comment] 2024-01-31 12:34
Just the content of `android/app`. If you can't publish it, send it to me via email (th address is available in package.json)

**Comment by AlixH** [comment] 2024-01-31 14:00
> Just the content of `android/app`. If you can't publish it, send it to me via email (the address is available in package.json)

Done :)

**Comment by zoontek** [comment] 2024-01-31 14:38
@AlixH Another things that does not seems to happen on non-Samsung phones.

**Comment by AlixH** [comment] 2024-01-31 14:46
Can you explain why the two android:theme are important ?

**Comment by zoontek** [comment] 2024-01-31 14:49
If set on application theme, the splash screen will be used on new activities / dialogs by default: https://github.com/zoontek/react-native-bootsplash/issues/516

Please fix your config according to the latest comment to see if this issue is not simply related to your file architecture.

**Comment by AlixH** [comment] 2024-01-31 14:52
> @AlixH Another things that does not seems to happen on non-Samsung phones.
> 
> Just checked your dir, and it's kinda weird, you don't have a `styles.xml` in `res/values`, but you have one in `res-core` (and also have two `AndroidManifest`).
> 
> Could you tried with a normal architecture / a clean react-native app to be sure that this is indeed a bug and not an issue you introduced? Because, if the system pick the necessary resources **before** your app booting, how would it know it has to search in your custom named directories?

In build.gradle, I specify to use both directories:
```
 sourceSets {
        main {
            res.srcDirs = ["src/main/res-core", "src/main/res"]
        }
    }
```

As of the manifest, AndroidManifest.xml is generated at build time by copying AndroidManifest-core.xml and simply replacing some placeholders

I will try what you said

**Comment by AlixH** [comment] 2024-01-31 15:23
Looking back to the history of my builds on play store, it seems the double splash issue appeared when introducing this new architecture. So the is an issue with multiple res dirs on Samsung I assume

**Comment by zoontek** [comment] 2024-01-31 15:32
Makes sense actually. Your app is defining the additional res folders, but the system is not aware of them. Closing this as following the default install does not create an issue.

**Closed by zoontek** 2024-01-31 15:32 UTC

**Comment by AlixH** [comment] 2024-01-31 16:06
In the end, the only reason I intoduced res-core is because I had no solution to avoid having git changes when generating the splash screen during build with this library because it adds the splash screen background color to res/colors

**Comment by AlixH** [comment] 2024-01-31 16:17
Jut being able to specify outputDir in the command line generator would be a massive feature

**Comment by AlixH** [comment] 2024-01-31 16:38
Having only one res directory does not solve the issue

**Comment by zoontek** [comment] 2024-01-31 16:41
> In the end, the only reason I intoduced res-core is because I had no solution to avoid having git changes when generating the splash screen during build with this library because it adds the splash screen background color to res/colors

`generate && git checkout path/to/the/file` to reset the changes
