### ISSUE TITLE
Splash screen flickers on fade

### ISSUE THREAD

**Issue by rob-johansen** [zoontek/react-native-bootsplash#427] opened 2023-02-15 05:56 UTC
### Bug summary

I'm testing on a Pixel 5, running Android 13. When the splash screen fades out, it occasionally flickers. I made a screen recording in an effort to demonstrate the problem but, curiously, the screen recording doesn't catch the flicker!

If I remove the `fade` property, the flicker goes away.

### Library version

4.5.0

### Environment info

```shell
info Fetching system and libraries information...
System:
    OS: macOS 13.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.03 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: Not Found
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2023.01.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
```


### Steps to reproduce

To reproduce the problem, just follow the steps in the README on a Pixel 5 running Android 13.

I don't have an iOS device, so I'm not sure if the issue is happening on an iPhone, but it doesn't happen in the simulator.


### Reproducible sample code

```js
To reproduce the problem, just follow the steps in the README on a Pixel 5 running Android 13.
```

**Comment by zoontek** [comment] 2023-02-15 14:05
@rob-johansen I noticed this too. It appears to be since React Native 0.71.
I will dig into the changes they made in order to find the cause of this.

**Comment by mikehuebner** [comment] 2023-03-01 23:19
Tried doing something they recommend but I'm pretty sure it is unrelated this this.

```
- (UIView *)createRootViewWithBridge:(RCTBridge *)bridge
                          moduleName:(NSString *)moduleName
                           initProps:(NSDictionary *)initProps
{
  UIView * rootView = [super createRootViewWithBridge:bridge moduleName:moduleName initProps:initProps];

  rootView.backgroundColor = [UIColor whiteColor];

  return rootView;
}
```

**Comment by gtokman** [comment] 2023-03-02 13:37
@mikehuebner that didn't work for me either. It appears to be the background color UIScene when looking at the view hierarchy inspector.

**Comment by zoontek** [comment] 2023-03-14 19:58
I investigated a bit, it does not appears to be related to React Native updates, but more to native Splash Screen implementation on Android 13. Flickers occurs occasionally, but I couldn't reproduce it on Android 12 😕

**Comment by altmshfkgudtjr** [comment] 2023-06-17 14:07
When I run the `RNBootSplash.hide` function, I remove the duration setting and the flicker is gone.

I hope my experience can help you solve your problem.

**Comment by zoontek** [comment] 2023-08-08 14:02
It should be fixed with https://github.com/zoontek/react-native-bootsplash/pull/475

**Comment by zoontek** [comment] 2023-08-21 22:09
Version 5.0.0 is available: https://github.com/zoontek/react-native-bootsplash/releases/tag/5.0.0

**Closed by zoontek** 2023-08-21 22:09 UTC
Labels: bug
