### ISSUE TITLE
Dark background is not showing correctly on android ( xiaomi phone ).

### ISSUE THREAD

**Issue by a-eid** [zoontek/react-native-bootsplash#662] opened 2024-12-14 01:23 UTC
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

I am trying to have the same splash screen on dark & light mode, but they seem to be different on dark mode ( background seem to be transparent ). 

```bash
npx react-native-bootsplash generate assets/app-logo.svg --logo-width=150 --dark-logo=assets/app-logo.svg --background=#FFF --dark-background=#FFF
```

![image](https://github.com/user-attachments/assets/6619275e-2e1a-41e0-bd88-6a101f1e63ed)

### Library version

6.3.2

### Environment info

```shell
info Fetching system and libraries information...
System:
  OS: macOS 15.1.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 1.09 GB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.1
    path: ~/n/bin/node
  Yarn:
    version: 1.22.22
    path: ~/n/bin/yarn
  npm:
    version: 10.8.2
    path: ~/n/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/ahmedelshentenawy/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.7
    path: /Users/ahmedelshentenawy/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. npx react-native-bootsplash generate assets/app-logo.svg --logo-width=150 --dark-logo=assets/app-logo.svg --background=#FFF --dark-background=#FFF 
2. open app & observe 

expected: both dark & light splash to have white background. 
actual: splash screen is transparent / grayish on dark mode. 

### Reproducible sample code

```js
N/A
```

**Comment by zoontek** [comment] 2024-12-14 11:07
@a-eid probably just a duplicate of https://github.com/zoontek/react-native-bootsplash/issues/497#issuecomment-2347177580

**Comment by zoontek** [comment] 2024-12-14 15:58
Invert the colors in dark mode, it should do the trick

**Comment by a-eid** [comment] 2024-12-15 02:26
@zoontek do you mean I should have the dark bg color set to `#000` ?

**Comment by zoontek** [comment] 2024-12-15 08:25
Both if you want to be readable.

Dark mode: white logo, dark background 
Light mode: dark logo, white background

**Comment by a-eid** [comment] 2024-12-15 09:47
thanks, is this a known xiaomi issue ? if so I am okay with it for now & think issue could be closed, right ?

**Comment by zoontek** [comment] 2024-12-15 10:02
Yes this is a MIUI issue, there's nothing we can do about it 😕

**Closed** 2024-12-15 16:39 UTC
Labels: bug
