### ISSUE TITLE
Show Option for the API

### ISSUE THREAD

**Issue by sean-pearson** [zoontek/react-native-bootsplash#425] opened 2023-02-01 23:29 UTC
### Why it is needed?

We use the splash screen when waiting for data to load, but there are cases such as when displaying a forced update screen that needs to be shown before loading new data. Having the ability to hide it and then show it later is useful. Maybe even an option to not show on the app instantly but later when called.

### Possible implementation

providing a show option that does the opposite of the hide. It can even have the animations.

**Comment by zoontek** [comment] 2023-02-02 09:35
Duplicate of https://github.com/zoontek/react-native-bootsplash/search?q=show&type=issues

It cannot be done with AndroidX core. I'm thinking about forking it at some point.

**Closed by zoontek** 2023-02-02 09:35 UTC
Labels: duplicate

**Comment by rashila-ssg** [comment] 2023-03-03 15:00
@zoontek I've added show api for ios and it's working perfectly fine on my application, if you think it's okay to add show option as ios specific feature, i can raise a pull request for it.

**Comment by zoontek** [comment] 2023-03-03 15:23
@rashila-ssg No, I want feature parity.
