### ISSUE TITLE
Android doesn't show RN red screens when Splashscreen is mounted

### ISSUE THREAD

**Issue by carl0shd** [zoontek/react-native-bootsplash#382] opened 2022-08-12 18:51 UTC
### Bug summary

Hi @zoontek, I implemented this library in my app, and works pretty well in IOS but when I launch it on Android, the app doesn't show any red screen (in my case, the red screen that tells me that my app doesn't find the Metro server) and also I can't see the development menu when I shake the phone to change the bundle location IP.

### Library version

4.3.1

### Environment info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 3.66 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/xc/h03v4t_n6xjfn4p75xpph5z80000gn/T/yarn--1660329843727-0.046735578081471774/node
    Yarn: 1.22.18 - /var/folders/xc/h03v4t_n6xjfn4p75xpph5z80000gn/T/yarn--1660329843727-0.046735578081471774/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/carlosvillalobos/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.4 => 0.69.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Use the example project and runs in android but don't open the RN Metro server, you should not see the red screen. (Tested in the simulator and a real device, Android 11 and Android 12)

### Reproducible sample code

```js
Should be reproducible with the example app in Android.
```

**Comment by zoontek** [comment] 2022-08-12 19:15
Duplicate of https://github.com/zoontek/react-native-bootsplash/issues/296

This can't be done, since the Splash screen is not handled by React Native itself and there is no equivalent to the `RCTJavaScriptDidFailToLoadNotification` iOS event on Android.

As the error are now logged in the console when running metro, if you see that it can't load the bundle, run `adb reverse tcp:8081 tcp:8081` ([doc](https://reactnative.dev/docs/debugging#debugging-on-a-device-with-chrome-developer-tools))

**Closed by zoontek** 2022-08-12 19:15 UTC
Labels: bug
