### ISSUE TITLE
Stuck On Splash - Android

### ISSUE THREAD

**Issue by animeshwebdeveloper** [zoontek/react-native-bootsplash#370] opened 2022-07-07 11:16 UTC
### Bug summary

react-native-bootsplash version: 4.2.3
react-native version: 0.68.2
Platform: android
OS version: 12.4
Stuck on the splash screen not moving to the next screen, It's working fine on the IOS Xcode simulator but not on Android Studio simulator .

### Library version

4.2.3

### Environment info

```shell
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1023 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Launching emulator...
info Successfully launched emulator.
info Installing the app...

> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at /Users/animeshshrivastava/Desktop/CUBERA-MAIN/mobile-app/jun_30/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_app package.json found at /Users/animeshshrivastava/Desktop/CUBERA-MAIN/mobile-app/jun_30/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_analytics:firebase.bom using default value: 30.1.0
:react-native-firebase_analytics package.json found at /Users/animeshshrivastava/Desktop/CUBERA-MAIN/mobile-app/jun_30/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_analytics:version set from package.json: 14.11.1 (14,11,1 - 14011001)
:react-native-firebase_analytics:android.compileSdk using custom value: 31
:react-native-firebase_analytics:android.targetSdk using custom value: 31
:react-native-firebase_analytics:android.minSdk using custom value: 23
:react-native-firebase_analytics:reactNativeAndroidDir /Users/animeshshrivastava/Desktop/CUBERA-MAIN/mobile-app/jun_30/node_modules/react-native/android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /Users/animeshshrivastava/Desktop/CUBERA-MAIN/mobile-app/jun_30/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using default value: 30.1.0
:react-native-firebase_app:play.play-services-auth using default value: 20.2.0
:react-native-firebase_app package.json found at /Users/animeshshrivastava/Desktop/CUBERA-MAIN/mobile-app/jun_30/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 14.11.1 (14,11,1 - 14011001)
:react-native-firebase_app:android.compileSdk using custom value: 31
:react-native-firebase_app:android.targetSdk using custom value: 31
:react-native-firebase_app:android.minSdk using custom value: 23
:react-native-firebase_app:reactNativeAndroidDir /Users/animeshshrivastava/Desktop/CUBERA-MAIN/mobile-app/jun_30/node_modules/react-native/android

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_5_API_33(AVD) - 13' for :app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 5s
108 actionable tasks: 6 executed, 102 up-to-date
info Connecting to the development server...
8081
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.cuberamobileapp/.MainActivity }
animeshshrivastava@Animeshs-MBP jun_30 %
```

### Steps to reproduce

It's on local only.

### Reproducible sample code

```js
It's on local only.
```

**Comment by zoontek** [comment] 2022-07-07 11:25
@animeshwebdeveloper Please post JS code. Also, are you sure this is not just a dev server issue? Like your app just doesn't load your JS bundle? 😅

**Comment by Zontex** [comment] 2022-07-10 13:44
@zoontek I have the same issue with android on variant release on a real device. on debug, it doesn't happen.

**Comment by zoontek** [comment] 2022-07-10 15:26
@Zontex Same as the issue author, without valid reproduction code, nothing can be done.

**Comment by zoontek** [comment] 2022-07-15 10:14
I'm closing this since there is no reproduction code and as it seems to not be a general issue with the library, it will probably be more suited to ask for help on StackOverflow.

**Closed by zoontek** 2022-07-15 10:14 UTC
Labels: bug

**Comment by akshgods** [comment] 2022-09-20 17:57
same happening with v 0.69 
stuck on splash only on android
