### ISSUE TITLE
Question: MainActivity.java Problem

### ISSUE THREAD

**Issue by efecantekin** [zoontek/react-native-bootsplash#165] opened 2020-10-08 06:56 UTC
# Bug report

## Summary

Hello,

I don't know what causes this problem, also this is bootsplash's bug, or not.
In my environment settings, I copy MainActicity.java file into myApp/test/ but when

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
    }
```

this part of MainActivity takes a part on both files(in com/x and com/x/test), build gives an error as R class not found.

When I remove onCreate method from com/x/MainActivity.java and it stays on com/x/test/MainActivity.java, it works with any problem.

Note: Without bootsplash, it works great and doesn't give any error.

Do you know anything about solving this interesting problem?

Thank you,rea
## Environment info

`react-native info` output:

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.16 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 2.2.6

**Comment by zoontek** [comment] 2020-10-08 07:36
@efecantekin  If the drawable.xml resource exists, it might be caused by the gradle cache. Try to clean it?

**Comment by efecantekin** [comment] 2020-10-08 11:26
Lots of time I tried ./gradle clean but never worked.
I share my MainActivity.java files, on main and test folders, below.

What I said before, if I remove onCreate method on com/MainActivity.java, it works. But don't know how can I manage this with dynamic environment changes.

**.com/MainActivity.java**
`package com.x.X;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;

import android.os.Bundle;
import android.util.Log;

import com.facebook.react.ReactActivity;
import com.zoontek.rnbootsplash.RNBootSplash; 

public class MainActivity extends ReactActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "xxx";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
    }
}
`

**.com/test/MainActivity.java**
`
package com.x.X.test;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;

import android.os.Bundle;
import android.util.Log;

import com.facebook.react.ReactActivity;
import com.zoontek.rnbootsplash.RNBootSplash; 

public class MainActivity extends ReactActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "xxx";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
    }
}
`

**Comment by zoontek** [comment] 2020-10-08 11:29
Try adding `import com.x.X.R;` in `com/x/X/test/MainActivity.java`

**Comment by efecantekin** [comment] 2020-10-08 12:54
> Try adding `import com.x.X.R;` in `com/x/X/test/MainActivity.java`

I was sure it wouldn't work but I tried for you.

/com/x/X/MainActivity.java:4: error: package com.x.X does not exist
import com.facebook.Fibabanka.R;
                             ^
/com/x/X/MainActivity.java:25: error: package R does not exist
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
                           ^

com/x/X/test/MainActivity.java:4: error: cannot find symbol
import com.x.X.R;
                              ^
  symbol:   class R
  location: package com.x.X
/com/x/X/MainActivity.java:4: error: cannot find symbol
import com.x.X.R;
                              ^
  symbol:   class R
  location: package com.x.X
/com/x/X/MainActivity.java:25: error: package R does not exist
        RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);

**Comment by zoontek** [comment] 2020-10-08 12:55
Anyway, I'm closing this since it's not related to the library. Sorry.

**Closed by zoontek** 2020-10-08 12:55 UTC

**Comment by Dauria1** [comment] 2021-06-13 11:04
Your package name in your AndroidManifest.xml is likely wrong
