### ISSUE TITLE
How to make fullscreen?

### ISSUE THREAD

**Issue by billnbell** [zoontek/react-native-bootsplash#294] opened 2021-12-08 22:11 UTC
### Why it is needed?

How do I switch style to be full screen and not icon in 4.0.2?

android/app/src/main/res/values/styles.xml

I used to have:
```
-  <style name="BootTheme" parent="AppTheme">
-    <item name="android:statusBarColor">@color/splashscreen_bg</item>
-    <item name="android:background">@drawable/bootsplash</item>
-  </style>
+    <!-- BootTheme should inherit from Theme.SplashScreen -->
+    <style name="BootTheme" parent="Theme.SplashScreen">
+      <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
+      <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
+      <item name="postSplashScreenTheme">@style/AppTheme</item>
+    </style>
```

**Comment by zoontek** [comment] 2021-12-08 23:22
Duplicate of https://github.com/zoontek/react-native-bootsplash/issues/283

**Closed by zoontek** 2021-12-08 23:22 UTC
Labels: feature request
