### ISSUE TITLE
Logo is half size on Samsung Galaxy device

### ISSUE THREAD

**Issue by RamProg** [zoontek/react-native-bootsplash#466] opened 2023-07-04 12:31 UTC
### Bug summary

Splash screen working fine on iOS. On Android, it looks fine on Pixel devices, but it looks half size in Samsung Galaxy S20+.

We were using v3 before and didn't have this issue. We migrated to v4 following all steps as per docs and started seeing this issue.

We regenerated the png with the command, and also tried the old ones. We also tried using an XML drawable and it always looks smaller on Samsung galaxy.

I found this very similar issue, but it never got a solution.https://github.com/zoontek/react-native-bootsplash/issues/410

### Library version

4.7.3

### Environment info

```shell
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 91.11 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Open the app on a Pixel Device
2. Open the app on a Samsung Galaxy
3. Notice a size difference in the logo

### Reproducible sample code

```js
<style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/brandRed</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>
    </style>
```

**Comment by zoontek** [comment] 2023-07-04 15:12
I don't have a Samsung to reproduce this, but maybe Samsung implements the Android SplashScreen API incorrectly.

**Comment by RamProg** [comment] 2023-07-04 15:15
I'll add to my backlog to try the example app on a Samsung device and see if the issue is there too.

**Comment by zoontek** [comment] 2023-08-22 08:32
@RamProg I made a test using Browserstack with v5. It does not seems to occur, but I'm not 100% sur as it records on 30 FPS. tried to spot the half size logo during the opening but I can't really see it.

If you have a physical device, please give it a try to confirm.

https://github.com/zoontek/react-native-bootsplash/assets/1902323/42c64005-58a2-4f68-84e5-d0602f68e900

**Comment by zoontek** [comment] 2023-08-24 09:24
I found this: https://issuetracker.google.com/issues/251807014

> Samsung aligned on splash screen sizing for One UI 5.0 (Android 13).

**Comment by nhutph** [comment] 2023-10-17 16:51
when you pr to master bro ?

**Comment by nhutph** [comment] 2023-10-18 01:41
@zoontek Sorry about that.

**Comment by nhutph** [comment] 2023-10-31 03:21
any update for issue or status pr for issue ?

**Comment by zoontek** [comment] 2023-10-31 08:33
It will be in 5.1.0 beta on wednesday (I have a day off)

**Comment by zoontek** [comment] 2023-11-01 16:37
I published a beta, so anyone can test it: https://github.com/zoontek/react-native-bootsplash/pull/505

**Comment by alabsi91** [comment] 2023-11-03 16:34
@zoontek Hey, I've recently upgraded to version 5 and encountered an issue with image zooming on the Samsung Galaxy S10. I wanted to inform you that I've tested the beta release, and it's working just as well as it did in version 4. Thank you.

**Comment by zoontek** [comment] 2023-11-03 17:00
@alabsi91 Perfect, thank for your feedback 🙂 I will probably release the stable `5.1.0` this weekend.

**Comment by alabsi91** [comment] 2023-11-03 17:10
@zoontek I'm sorry, but I just found an issue. I barely noticed it, when navigating using React Navigation, the splash screen appears during the transition between the screens for a split second.

**Comment by zoontek** [comment] 2023-11-03 17:19
@alabsi91 please provide a simple reproduction

**Comment by alabsi91** [comment] 2023-11-03 17:51
## repo: https://github.com/alabsi91/splash-screen-android-issue
https://github.com/zoontek/react-native-bootsplash/assets/58077449/8f509908-3f2c-44c5-a7b4-90b5343b5b6f

**Comment by zoontek** [comment] 2023-11-03 18:03
@alabsi91 perfect, thanks a lot, I will have a look in the following days 🙏

**Comment by zoontek** [comment] 2023-11-04 16:41
@alabsi91 I tried a lot of things, but keeping a `View` creating a lot of issues (the one you mention, but also some flicker on hide), so I rolled back to `Dialog` implem (with an attempt to fix https://github.com/zoontek/react-native-bootsplash/issues/498). Latest version is `5.1.0-beta.2`, give it a try but it should works correctly now (including on Samsungs with OneUI v4)

**Comment by alabsi91** [comment] 2023-11-04 20:14
@zoontek 🙌 Thank you for your amazing work! I've tested the new fix on a Galaxy S10 device with One UI version 4.1, and everything is looking great so far 👍

**Comment by zoontek** [comment] 2023-11-07 21:18
5.1.0 stable is [here](https://github.com/zoontek/react-native-bootsplash/releases/tag/5.1.0). I'm closing this issue, as I cannot fix the size on the system thread - at least the size is stable now.

**Closed by zoontek** 2023-11-07 21:18 UTC
Labels: bug

**Comment by alabsi91** [comment] 2023-11-09 12:56
Hey @zoontek , I encountered the same issue, but this time it only occurs when using the `@react-native-community/blur` BlurView. I'm not entirely sure why, but I suspect that on Android, they use a root View as an overlay color. It's not a significant issue, but I wanted to inform you. I have updated the repository, so you can take a look at it if you're interested.

## Repo: https://github.com/alabsi91/splash-screen-android-issue


https://github.com/zoontek/react-native-bootsplash/assets/58077449/d219c0e1-70ec-4d3c-8fac-0c4f384c7a5c

**Comment by huextrat** [comment] 2023-11-10 21:21
@zoontek  `5.1.0` was working fine, but it seems that the issue is still here in `5.1.1` ? 🤔

**Comment by zoontek** [comment] 2023-11-11 01:28
@huextrat Are you using brand image? That's the only change for the samsungs from 5.1.0 -> 5.1.1

I know they size the logo incorrectly, but I found no info about them sizing the brand image incorrectly too

**Comment by huextrat** [comment] 2023-11-14 14:04
> @huextrat Are you using brand image? That's the only change for the samsungs from 5.1.0 -> 5.1.1
> 
> I know they size the logo incorrectly, but I found no info about them sizing the brand image incorrectly too

Ok seems to working fine on `5.1.2` 🤷  I may have look at the wrong version. Anyway, thanks :)

**Comment by zoontek** [comment] 2023-11-14 14:52
@huextrat Maybe a cache issue? Even on `5.1.1`, the code responsible for picking the OneUI v4 specific drawable didn't change 🤷🏻‍♂️

**Comment by dkahdwk** [comment] 2024-01-19 05:05
@zoontek 
On Galaxy Note 10 devices, the image size is still significantly reduced. I really wanted to see if there was a problem with the react-native-bootsplash library, so I ran other popular apps on that device and was surprised to find that all applications experienced a significant reduction in splash image size. This issue is not this library issue, but as I said, it's probably an Android issue.
So I decided to give up on this issue🥹

**Comment by zoontek** [comment] 2024-01-19 08:51
Probably that Samsung computer the size in another incorrect way on Note device.
At some point, we can patch it (here the fix target OneUI v4, are we supposed to a patched layout per device?) 😞. At least they fixed it on Android 13.

**Comment by dkahdwk** [comment] 2024-01-19 08:59
@zoontek I forgot it was about OneUI v4....i just wanted to share. Anyway, thank you for your hard work!

**Comment by NiharR27** [comment] 2024-01-19 09:28
Hi @zoontek, Thanks for the awesome package :)! this might not be the correct issue (i got here from some other issue relating to double splash screen,etc). We had the version `v5.0.3` installed and that worked fine. But before going Christmas we bumped the version to `v5.1.3`, this has fixed the above problem of double logos on android (it was all good on iOS). It however is stretching logos now - it's almost like they are fixed in a certain width and height with stretching in it). Have you by any chance come across this issue? Thanks again, have a nice week!

**Comment by zoontek** [comment] 2024-01-19 09:59
@NiharR27 What phone do you have? A Samsung on OneUI v4?

**Comment by NiharR27** [comment] 2024-01-19 10:04
> @NiharR27 What phone do you have? A Samsung on OneUI v4?

I tested on Samsung Galaxy S21 5G OS Version 13 (gotta check the above, not really sure about oneUI v4).

Currently i am testing on Google Pixel 5 API 30 Sim

**Comment by zoontek** [comment] 2024-01-19 10:05
So no, not the same issue. Please open a new one with **a solid reproduction**.

**Comment by NiharR27** [comment] 2024-01-19 10:06
> So no, not the same issue. Please open a new one with **a solid reproduction**.

ok 👌🏽 will do thanks.
