### ISSUE TITLE
[Android] Splashscreen stuck and won't run App.tsx #460

### ISSUE THREAD

**Issue by fellipesnoww** [zoontek/react-native-bootsplash#460] opened 2023-06-07 21:03 UTC
### Bug summary

Hey, guys!

After installing the lib and testing it on iOS, everything works perfectly.

On Android, the splash screen was displayed but remained displayed and the hide() command in App.tsx was not executed.

I tried it on emulators with android versions 11 and 12 and both had the same problem.

If you want try execute my app, here's my repo: https://github.com/fellipesnoww/github-users/tree/bug-fixes-improvements

See the video below showing the app's behavior:

https://drive.google.com/file/d/10fj4dVlulm_q8EtJqmq6olnnwuUZdG5D/view?usp=sharing

PS: There were cases in other apps that I worked on that it took more than 40 seconds to run the App.tsx. (Not the case cited in the issue)

### Library version

4.7.2

### Environment info

```shell
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 310.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2023.02.20.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/fellipeneves/.rvm/rubies/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Execute app;
2. Open in android device or simulator;
3. Wait few seconds

### Reproducible sample code

```js
import React, {useEffect} from 'react';
import {ThemeProvider} from 'styled-components';

import {APP_THEME} from './src/global/styles/theme';
import Routes from './src/routes';
import {UsersProvider} from './src/contexts/UsersProvider';
import RNBootSplash from "react-native-bootsplash";

function App(): JSX.Element {
  useEffect(() => {
    console.log("App mounted")
    RNBootSplash.hide({duration: 1000, fade: true})
  },[]);

  return (
    <ThemeProvider theme={APP_THEME}>
      <UsersProvider>
        <Routes /> {/* or other component */}
      </UsersProvider>
    </ThemeProvider>
  );
}

export default App;
```

**Comment by zoontek** [comment] 2023-06-07 21:49
@fellipesnoww Are you sure this isn't just because you forgot to do an adb reverse and the JS bundle isn't loaded? It's a common mistake.

**Comment by fellipesnoww** [comment] 2023-06-08 12:47
@zoontek  Thanks for the quick response. Forgot to mention that I tried to run the command `adb reverse tcp:8081 tcp:8081` but unfortunately doesn't work.

And tried to follow some comments from that issue https://github.com/zoontek/react-native-bootsplash/issues/423

**Comment by zoontek** [comment] 2023-06-08 12:50
@fellipesnoww I'm nearly sure that's only because of that. React native hangs to download the JS bundle, then timeout. As the splash screen is visible this whole time, you think there's an issue with the library.

If you build it in `release` mode, the JS bundle will be included in the app and it should be instant, confirming that the issue come from your setup and that the communication between metro and the emulator / device is broken.

**Closed** 2023-06-08 15:05 UTC

**Comment by dkahdwk** [comment] 2023-07-03 00:46
@zoontek The same issue appears, but I don't know the cause.
It's been working well for the past few months, but suddenly it's not working.
